# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Karma' do

pod 'AFNetworking', '~> 2.5'
pod 'Facebook-iOS-SDK', '~> 4.1'
pod 'CardIO', '~> 5.0'

end

target 'KarmaTests' do

end

