# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Karma' do

pod 'AFNetworking', '~> 2.5'
pod 'FBSDKCoreKit', '~> 4.2'
pod 'FBSDKLoginKit', '~> 4.2'
pod 'CardIO', '~> 5.0'

end

target 'KarmaTests' do

end

